blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/ABurdin/mongodb-selective-export/discussions
    about: Please discuss non bug-related topics there
